# Generated by Django 4.2.6 on 2023-10-12 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_expirationdate'),
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.client'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sell',
            name='products',
            field=models.TextField(default='[]'),
        ),
    ]
